# To improve accuracy, we can add synonyms pertaining to each word (like 'risk', 'investment' etc)

import pandas as pd

risk = pd.DataFrame(['risk', 'danger', 'exposure', 'hazard', 'liability', 'opportunity', 'peril', 'possibility', 'prospect', 'uncertainity', 'accident', 'contingency', 'flyer', 'fortuity', 'fortune', 'gamble', 'header', 'jeopardy', 'luck', 'openness', 'plunge', 'speculation', 'stab', 'venture', 'wager', 'exposedness', 'liable'])
investment = pd.DataFrame(['investment', 'asset', 'contribution', 'expenditure', 'investment', 'expense', 'finance', 'financing', 'grant', 'loan', 'money', 'property', 'purchase', 'stake', 'transaction', 'venture', 'advance', 'ante', 'backing', 'bail', 'endowment', 'flutter', 'hunch', 'inside', 'interests', 'investing', 'piece', 'plunge', 'spec', 'speculation', 'stab', 'smart money', 'vested interests'])
entrepreneurship = pd.DataFrame(['entrepreneurship', 'administrator', 'contractor', 'executive', 'manager', 'producer', 'backer', 'businessperson', 'businessman', 'founder', 'industrialist', 'organiser', 'promoter', 'undertaker', 'enterprise', 'entrepreneurialism', 'entrepreneurism', 'capital', 'capitalism', 'industrailism'])
venture = pd.DataFrame(['venture', 'deal', 'endeavor', 'enterprise', 'investment', 'project', 'undertaking', 'adventure', 'baby', 'chance', 'essay', 'exploit', 'feat', 'hazard', 'header', 'peril', 'jeopardy', 'peril', 'proposition', 'pursuit', 'setup', 'shot', 'speculation', 'stab', 'stake', 'test', 'thing', 'trial', 'wager', 'product'])
novel = pd.DataFrame(['novel', 'different', 'innovative', 'odd', 'offbeat', 'colourful', 'peculiar', 'strange', 'unique', 'unusual', 'contemporary', 'avant-grade', 'now', 'recent', 'singular', 'cutting-edge', 'atypical', 'breaking-new', 'ground', 'farcry', 'fresh', 'funky', 'justout', 'modernistic', 'neoteric', 'new-fashioned', 'newfangled', 'rare', 'uncommon', 'unfamiliar'])
innovation = pd.DataFrame(['innovation', 'modernisation', 'addition', 'alteration', 'contraption', 'departure', 'deviation', 'introduction', 'modernism', 'modification', 'mutation', 'newness', 'notion', 'permutation', 'shift', 'variation', 'vicissitude', 'wrinkle', 'cutting-edge', 'last word', 'latest thing', 'leading edge'])
patent = pd.DataFrame(['patent', 'charter', 'concession', 'license', 'privilege', 'protection', 'control', 'franchise', 'limitation'])
divestiture = pd.DataFrame(['divestiture', 'disinvestment', 'divestment', 'dispossession', 'privation', 'divesture'])
acquire = pd.DataFrame(['acquire', 'achieve', 'amass', 'bring-in', 'buy', 'collect', 'earn', 'gain', 'get', 'have', 'pickup', 'promote', 'win', 'access', 'annex', 'attain', 'catch', 'cop', 'corral', 'gather', 'grab', 'hustle', 'land', 'procure', 'snag', 'secure', 'wangle', 'get hands on', 'get hold of', 'possess', 'possession'])
diversify = pd.DataFrame(['diversify', 'expand', 'transform', 'alter', 'assort', 'change', 'mix', 'modify', 'varigate', 'vary'])
failure = pd.DataFrame(['failure', 'bankruptcy', 'breakdown', 'collapse', 'decline', 'defeat', 'deficiency', 'deterioration', 'failing', 'loss', 'misstep', 'abortion', 'bomb', 'botch', 'bungle', 'bust', 'checkmate', 'decay', 'deficit', 'downfall', 'fiasco', 'flop', 'frustration', 'implosion', 'inadequacy', 'lemon', 'loser', 'mess', 'misadventure', 'miscarriage', 'nonperformance', 'overthrow', 'rout', 'rupture', 'stalemate', 'stoppage', 'turkey', 'washout', 'wreck'])
success = pd.DataFrame(['success', 'accomplisment', 'achievement', 'advance', 'benefit', 'boom', 'fame', 'gain', 'happiness', 'profit', 'progress', 'prosperity', 'realisation', 'triumph', 'victory', 'win', 'arrival', 'ascendency', 'attainment', 'clover', 'consummation', 'eminence', 'fortune', 'fruition', 'hit', 'killing', 'laughter', 'maturation', 'reward', 'savvy', 'sensation', 'snap', 'strike', 'successfulness', 'walkaway', 'walkover'])
synonyms = pd.concat([risk, investment, entrepreneurship, venture, novel, innovation, patent, divestiture, acquire, diversify, failure, success], ignore_index=True, axis=1)
